/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.List;
import persistencia.entidades.Cliente;
import persistencia.entidades.Produto;
import persistencia.entidades.Venda;
import visao.processos.GerandoRelatorio;

/**
 *
 * @author Bruno
 */
public class JanelaGerandoRelatorio extends javax.swing.JDialog {
    
    private GerandoRelatorio processo;
    
    /**
     * Creates new form JanelaGerandoRelatorio
     * @param parent
     * @param lista
     * @param modal
     */
    public JanelaGerandoRelatorio(java.awt.Frame parent, List<Produto> lista, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        processo = new GerandoRelatorio(this, lista);
        processo.start();
    }
    
    /**
     *
     * @param parent
     * @param lista
     * @param modal
     */
    public JanelaGerandoRelatorio(java.awt.Frame parent, List<Cliente> listaClientes, boolean modal, String tipo) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        processo = new GerandoRelatorio(this, listaClientes,tipo);
        processo.start();
    }

    public JanelaGerandoRelatorio(java.awt.Frame parent, Venda venda, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        jtexto.setText("Gerando a nota...");
        processo = new GerandoRelatorio(this, venda);
        processo.start();
    }
    
    public JanelaGerandoRelatorio(java.awt.Frame parent, List<Venda> lista, String inicio, String fim, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        processo = new GerandoRelatorio(this, lista, inicio, fim);
        processo.start();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtexto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtexto.setText("Gerando Relatorio...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jtexto)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jtexto)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        processo.stop();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jtexto;
    // End of variables declaration//GEN-END:variables
}
