/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.FachadaControle;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.entidades.Cliente;
import persistencia.entidades.Veiculo;

/**
 *
 * @author Bruno
 */
public class JanelaEditarClientes extends javax.swing.JDialog {
    private java.awt.Frame pai;
    
    private List<Veiculo> veiculos;
    private List<Veiculo> apagados;
    
    private Cliente cliente = null;
    /**
     * Creates new form JanelaCadastroUsuario
     */
//    public JanelaEditarClientes(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
//        pai = parent;
//        initComponents();
//        this.setLocationRelativeTo(null);
//        veiculos = new ArrayList<>();
//        jnome.requestFocus();
//    }
    
    public JanelaEditarClientes(java.awt.Frame parent, boolean modal,Cliente cliente) {
        super(parent, modal);
        pai = parent;
        initComponents();
        this.setLocationRelativeTo(null);
        veiculos = cliente.getVeiculos();
        jnome.requestFocus();
        this.cliente = cliente;
        apagados = new ArrayList<>();
        
        
         jcodigo.setText(this.cliente.getCodigo()+"");
         jnome.setText(this.cliente.getNome());
         japelido.setText(this.cliente.getApelido());
         jnascimento.setText(this.cliente.getNascimento());
         jendereco.setText(this.cliente.getEndereco());
         jnumero.setText(this.cliente.getNumero()+"");
         jbairro.setText(this.cliente.getBairro());
         jcep.setText(this.cliente.getCep());
         jcpf.setText(this.cliente.getCpf());
         jrg.setText(this.cliente.getRg());
         //jcodigo.setText(this);
         jtelefone.setText(this.cliente.getTelefone());
         jcelular.setText(this.cliente.getCelular());
         jemail.setText(this.cliente.getEmail());
         if(this.cliente.isTemPendencia()){
             jRadioButton1.setSelected(true);
             jRadioButton2.setSelected(false);
         }else{
             jRadioButton1.setSelected(false);
             jRadioButton2.setSelected(true);
         }
         jTextArea1.setText(this.cliente.getObservacao());
         
         DefaultTableModel modelo = (DefaultTableModel) jtabelaveiculos.getModel();
            //Limpa a tabela antes de adicionar os novos dados
//            int tam = modelo.getRowCount();
//            for(int i=0;i<tam;i++){
//                modelo.removeRow(0);
//            }
            for(Veiculo veiculo : this.cliente.getVeiculos()){
               String[] linha = new String[4];
                linha[0] = veiculo.getPlaca();
                linha[1] = veiculo.getModelo();
                linha[2] = veiculo.getAno()+"";
                linha[3] = veiculo.getCor();
                modelo.addRow(linha);
            }
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jnome = new javax.swing.JTextField();
        japelido = new javax.swing.JTextField();
        jendereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtelefone = new javax.swing.JFormattedTextField();
        jcelular = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jnascimento = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jnumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcep = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jsexo = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jbairro = new javax.swing.JTextField();
        jcpf = new javax.swing.JFormattedTextField();
        jrg = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jcodigo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jbutaosalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelaveiculos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDITAR DE CLIENTE");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("NOME:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("APELIDO:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ENDEREÇO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CPF:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("RG:");

        jnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnomeActionPerformed(evt);
            }
        });
        jnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jnomeKeyPressed(evt);
            }
        });

        japelido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        japelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                japelidoKeyPressed(evt);
            }
        });

        jendereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenderecoActionPerformed(evt);
            }
        });
        jendereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jenderecoKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("TELEFONE:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CELULAR:");

        try {
            jtelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtelefoneActionPerformed(evt);
            }
        });
        jtelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtelefoneKeyPressed(evt);
            }
        });

        try {
            jcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jcelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcelularKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("NASCIMENTO:");

        try {
            jnascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jnascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jnascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jnascimentoKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nº");

        jnumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jnumeroKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("CEP:");

        try {
            jcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jcep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcepKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("E-MAIL:");

        jemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jemailKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("SEXO:");

        jsexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        jsexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsexoKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("BAIRRO:");

        jbairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbairroKeyPressed(evt);
            }
        });

        try {
            jcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jcpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcpfKeyPressed(evt);
            }
        });

        jrg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrgKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("CÓDIGO:");

        jcodigo.setEditable(false);
        jcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("PENDÊNCIAS:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("sim");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("não");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(japelido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jemail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jcep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrg, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addComponent(jbairro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jendereco, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jnumero))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnome)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(japelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel10)
                        .addComponent(jcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jrg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbutaosalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar.png"))); // NOI18N
        jbutaosalvar.setText("SALVAR");
        jbutaosalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaosalvarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Veículos do Cliente"));

        jtabelaveiculos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtabelaveiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Ano", "Cor"
            }
        ));
        jScrollPane1.setViewportView(jtabelaveiculos);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lixeira2.png"))); // NOI18N
        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações Adicionais"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbutaosalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jbutaosalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbutaosalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaosalvarActionPerformed

            this.editar();
            
            for(Veiculo v : apagados){
                FachadaControle.getFachadaControle().removerVeiculo(v);
                
            }
        
    }//GEN-LAST:event_jbutaosalvarActionPerformed

    private void jnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            japelido.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jnomeKeyPressed

    private void japelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_japelidoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jnascimento.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }
    }//GEN-LAST:event_japelidoKeyPressed

    private void jenderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jenderecoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jnumero.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jenderecoKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Veiculo veiculo = new Veiculo();
        JanelaCadastroVeículos janelaveiculo = new JanelaCadastroVeículos(pai,true,veiculo);
        janelaveiculo.setVisible(true);
        FachadaControle.getFachadaControle().salvarVeiculo(veiculo);
        veiculos.add(veiculo);        
        this.meteNaTabela(veiculo);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenderecoActionPerformed

    private void jtelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtelefoneActionPerformed

    private void jnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnomeActionPerformed

    private void jnascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnascimentoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jendereco.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jnascimentoKeyPressed

    private void jnumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnumeroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbairro.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jnumeroKeyPressed

    private void jbairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbairroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcep.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jbairroKeyPressed

    private void jcepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcepKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcpf.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jcepKeyPressed

    private void jcpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcpfKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrg.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jcpfKeyPressed

    private void jrgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrgKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jsexo.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jrgKeyPressed

    private void jsexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsexoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtelefone.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jsexoKeyPressed

    private void jtelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtelefoneKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcelular.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jtelefoneKeyPressed

    private void jcelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcelularKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jemail.requestFocus();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jcelularKeyPressed

    private void jemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jemailKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                this.dispose();
            }
        
    }//GEN-LAST:event_jemailKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = jtabelaveiculos.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jtabelaveiculos.getModel();
        modelo.removeRow(i);
        apagados.add(veiculos.remove(i));
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void meteNaTabela(Veiculo veiculo){
        DefaultTableModel modelo = (DefaultTableModel) jtabelaveiculos.getModel();
            //Limpa a tabela antes de adicionar os novos dados
//            int tam = modelo.getRowCount();
//            for(int i=0;i<tam;i++){
//                modelo.removeRow(0);
//            }
            
               String[] linha = new String[4];
                linha[0] = veiculo.getPlaca();
                linha[1] = veiculo.getModelo();
                linha[2] = veiculo.getAno()+"";
                linha[3] = veiculo.getCor();
                modelo.addRow(linha);

    }
    
    public void editar(){
        
        cliente.setNome(jnome.getText().toUpperCase());
        cliente.setApelido(japelido.getText().toUpperCase());
        cliente.setEndereco(jendereco.getText().toUpperCase());
        cliente.setNascimento(jnascimento.getText());
        cliente.setNumero(Integer.parseInt(jnumero.getText()));
        cliente.setBairro(jbairro.getText().toUpperCase());
        cliente.setCep(jcep.getText());
        cliente.setCpf(jcpf.getText());
        cliente.setRg(jrg.getText());
        cliente.setEmail(jemail.getText());
        cliente.setSexo(jsexo.getSelectedItem().toString());
        cliente.setTelefone(jtelefone.getText());
        cliente.setCelular(jcelular.getText());
        cliente.setTemPendencia(jRadioButton1.isSelected());
        cliente.setObservacao(jTextArea1.getText());
        
        cliente.setVeiculos(veiculos);
        
        FachadaControle.getFachadaControle().editarCliente(cliente);
        
        jcodigo.setText(cliente.getCodigo()+"");
        jnome.setText(cliente.getNome());
        japelido.setText(cliente.getApelido());
        jendereco.setText(cliente.getEndereco());
        jbairro.setText(cliente.getBairro());
        
        
        JOptionPane.showMessageDialog(null, "Cliente editado com sucesso!");
        this.dispose();
    }
    
    public void salvar(){
        
        
        Cliente cli = new Cliente();
        
        cli.setNome(jnome.getText().toUpperCase());
        cli.setApelido(japelido.getText().toUpperCase());
        cli.setEndereco(jendereco.getText().toUpperCase());
        cli.setNascimento(jnascimento.getText());
        cli.setNumero(Integer.parseInt(jnumero.getText()));
        cli.setBairro(jbairro.getText().toUpperCase());
        cli.setCep(jcep.getText());
        cli.setCpf(jcpf.getText());
        cli.setRg(jrg.getText());
        cli.setEmail(jemail.getText());
        cli.setSexo(jsexo.getSelectedItem().toString());
        cli.setTelefone(jtelefone.getText());
        cli.setCelular(jcelular.getText());
        
        cli.setTemPendencia(this.jRadioButton1.isSelected());
        cli.setObservacao(this.jTextArea1.getText());
        
        cli.setVeiculos(this.veiculos);
        
        try {
            
            
            cli = FachadaControle.getFachadaControle().cadastrarCliente(cli);
            
            jcodigo.setText(cli.getCodigo()+"");
            jnome.setText(cli.getNome());
            japelido.setText(cli.getApelido());
            jendereco.setText(cli.getEndereco());
            jbairro.setText(cli.getBairro());
            
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the dialog
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                JanelaCadastroUsuario dialog = new JanelaCadastroUsuario(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField japelido;
    private javax.swing.JTextField jbairro;
    private javax.swing.JButton jbutaosalvar;
    private javax.swing.JFormattedTextField jcelular;
    private javax.swing.JFormattedTextField jcep;
    private javax.swing.JTextField jcodigo;
    private javax.swing.JFormattedTextField jcpf;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jendereco;
    private javax.swing.JFormattedTextField jnascimento;
    private javax.swing.JTextField jnome;
    private javax.swing.JTextField jnumero;
    private javax.swing.JFormattedTextField jrg;
    private javax.swing.JComboBox jsexo;
    private javax.swing.JTable jtabelaveiculos;
    private javax.swing.JFormattedTextField jtelefone;
    // End of variables declaration//GEN-END:variables
}
