/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.auxiliar.Arquivo;
import controle.FachadaControle;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.entidades.Item;
import persistencia.entidades.ItensPedido;
import persistencia.entidades.Pedido;

/**
 *
 * @author Bruno
 */
public class JanelaConsultaPedidos extends javax.swing.JDialog {
    
    private List<Pedido> lista;
        
    /**
     * Creates new form JanelaConsultaProdutos
     */
    public JanelaConsultaPedidos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.lista = null;
        jtodos.setSelected(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jtodos = new javax.swing.JRadioButton();
        jpendentes = new javax.swing.JRadioButton();
        jatrasados = new javax.swing.JRadioButton();
        jconcluidos = new javax.swing.JRadioButton();
        jcancelados = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaPesquisa = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabelaItens = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdataPedido = new javax.swing.JTextField();
        jdataPrevista = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtotalPedido = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE PEDIDOS");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Período das Vendas"));
        jPanel1.setToolTipText("Pesquisa");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa2.png"))); // NOI18N
        jButton7.setText("BUSCAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jtodos);
        jtodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtodos.setText("Todos os Pedidos");

        buttonGroup1.add(jpendentes);
        jpendentes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpendentes.setText("Pedidos Pendentes");

        buttonGroup1.add(jatrasados);
        jatrasados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jatrasados.setText("Pedidos Atrasados");

        buttonGroup1.add(jconcluidos);
        jconcluidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jconcluidos.setText("Pedidos Concluídos");

        buttonGroup1.add(jcancelados);
        jcancelados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcancelados.setText("Pedidos Cancelados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtodos)
                .addGap(28, 28, 28)
                .addComponent(jconcluidos)
                .addGap(54, 54, 54)
                .addComponent(jpendentes)
                .addGap(51, 51, 51)
                .addComponent(jatrasados)
                .addGap(38, 38, 38)
                .addComponent(jcancelados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtodos)
                    .addComponent(jpendentes)
                    .addComponent(jatrasados)
                    .addComponent(jconcluidos)
                    .addComponent(jcancelados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jTabelaPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "FORNECEDOR", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaPesquisaMouseClicked(evt);
            }
        });
        jTabelaPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabelaPesquisaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaPesquisa);
        jTabelaPesquisa.getColumnModel().getColumn(0).setResizable(false);
        jTabelaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTabelaPesquisa.getColumnModel().getColumn(1).setResizable(false);
        jTabelaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTabelaPesquisa.getColumnModel().getColumn(2).setResizable(false);
        jTabelaPesquisa.getColumnModel().getColumn(2).setPreferredWidth(50);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Pedido"));

        jtabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Preço", "Qtd", "Total Item"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtabelaItens);
        jtabelaItens.getColumnModel().getColumn(0).setResizable(false);
        jtabelaItens.getColumnModel().getColumn(0).setPreferredWidth(200);
        jtabelaItens.getColumnModel().getColumn(1).setResizable(false);
        jtabelaItens.getColumnModel().getColumn(1).setPreferredWidth(30);
        jtabelaItens.getColumnModel().getColumn(2).setResizable(false);
        jtabelaItens.getColumnModel().getColumn(2).setPreferredWidth(10);
        jtabelaItens.getColumnModel().getColumn(3).setResizable(false);
        jtabelaItens.getColumnModel().getColumn(3).setPreferredWidth(20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("DATA PEDIDO:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("DATA PREVISTA:");

        jdataPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdataPedido.setToolTipText("");

        jdataPrevista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdataPrevista.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("TOTAL PEDIDO:");

        jtotalPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdataPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jdataPrevista))
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtotalPedido)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jdataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jdataPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButton6.setText("FECHAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jButton5.setText("IMPRIMIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jButton1.setText("RECEBER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Parar.png"))); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabelaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaPesquisaMouseClicked
        this.selecionarItem();
        
    }//GEN-LAST:event_jTabelaPesquisaMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTabelaPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaPesquisaKeyPressed
//        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
//            //this.mandarProdutoPraVenda();
//        }else if(evt.getKeyCode() == KeyEvent.VK_UP){
//            int sel = jTabelaPesquisa.getSelectedRow();
//            if(sel > 0){
//                sel--;
//            }
//            this.selecionarItem();
//        }else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
//            int sel = jTabelaPesquisa.getSelectedRow();
//            if(sel < jTabelaPesquisa.getModel().getRowCount()){
//                sel++;
//            }
//            this.selecionarItem();
//        }
    }//GEN-LAST:event_jTabelaPesquisaKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.buscaPedido();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int codigo = Integer.parseInt((String)jTabelaPesquisa.getValueAt(jTabelaPesquisa.getSelectedRow(), 0));
            Pedido pedido = FachadaControle.getFachadaControle().getPedido(codigo);
            if(!pedido.getStatus().equals(Pedido.CANCELADO)){
                pedido.setStatus(Pedido.CONCLUIDO);
                FachadaControle.getFachadaControle().modificarStatus(pedido);
                this.buscaPedido();
                JOptionPane.showMessageDialog(null, "Pedido recebido com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "O pedido já foi cancelado!");
            }
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Selecione um pedido!");
        } catch (SQLException ex) {
            Logger.getLogger(JanelaConsultaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            int codigo = Integer.parseInt((String)jTabelaPesquisa.getValueAt(jTabelaPesquisa.getSelectedRow(), 0));
            Pedido pedido = FachadaControle.getFachadaControle().getPedido(codigo);
            if(!pedido.getStatus().equals(Pedido.CONCLUIDO)){
                pedido.setStatus(Pedido.CANCELADO);
                FachadaControle.getFachadaControle().modificarStatus(pedido);
                this.buscaPedido();
                JOptionPane.showMessageDialog(null, "Pedido cancelado com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Pedido não pode ser cancelado!");
            }
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Selecione um pedido!");
        } catch (SQLException ex) {
            Logger.getLogger(JanelaConsultaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            FachadaControle.getFachadaControle().gerarRelatorioPedidos((ArrayList<Pedido>) this.lista);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    public void selecionarItem(){
        int sel = jTabelaPesquisa.getSelectedRow();
        Pedido pedido = lista.get(sel);
                
        DefaultTableModel model = (DefaultTableModel) jtabelaItens.getModel();
        //Limpa a tabela antes de adicionar os novos dados
        int tam = model.getRowCount();
        for(int i=0;i<tam;i++){
            model.removeRow(0);
        }
        
        DateFormat df = new SimpleDateFormat("dd/mm/yyyy");
        String dataPed = df.format(pedido.getDataPedido());
        String dataPrev = df.format(pedido.getDataPrevista());
        jdataPedido.setText(dataPed);
        jdataPrevista.setText(dataPrev);
        jtotalPedido.setText("R$ "+pedido.getTotal());
        
        for (ItensPedido item : pedido.getItens()) {
            String[] linha = new String[4];
            linha[0] = item.getProduto().getDescricao();
            linha[1] = "R$ "+item.getPreco();
            linha[2] = item.getQuantidade()+"";
            linha[3] = "R$ "+item.getTotal();
            model.addRow(linha);
        }
    }
    
    public void buscaPedido(){
        
        DefaultTableModel model1 = (DefaultTableModel) jtabelaItens.getModel();
        //Limpa a tabela antes de adicionar os novos dados
        int tam = model1.getRowCount();
        for(int i=0;i<tam;i++){
            model1.removeRow(0);
        }
        
        jdataPedido.setText("");
        jdataPrevista.setText("");
        jtotalPedido.setText("");
        
        DefaultTableModel model = (DefaultTableModel) jTabelaPesquisa.getModel();
        //Limpa a tabela antes de adicionar os novos dados
        tam = model.getRowCount();
        for(int i=0;i<tam;i++){
            model.removeRow(0);
        }
        
        
        try {
            if(jtodos.isSelected()){
                lista = FachadaControle.getFachadaControle().consultaPedidos();
            }else if(jconcluidos.isSelected()){
                lista = FachadaControle.getFachadaControle().consultaPedidosPorStatus(Pedido.CONCLUIDO);
            }else if(jpendentes.isSelected()){
                lista = FachadaControle.getFachadaControle().consultaPedidosPorStatus(Pedido.PENDENTE);
            }else if(jcancelados.isSelected()){
                lista = FachadaControle.getFachadaControle().consultaPedidosPorStatus(Pedido.CANCELADO);
            }else{
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                lista = FachadaControle.getFachadaControle().consultaPedidosAtrasados(sdf.format(new Date()));
            }
            
            for(Pedido pedido : lista){
                String[] linha = new String[9];
                linha[0] = pedido.getCodigo()+"";
                linha[1] = pedido.getFornecedor().getNome();
                linha[2] = pedido.getStatus();
                
                model.addRow(linha);
            }
            
            
            
            jTabelaPesquisa.requestFocus();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(JanelaConsultaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(JanelaConsultaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the dialog
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                JanelaConsultaProdutos dialog = new JanelaConsultaProdutos(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabelaPesquisa;
    private javax.swing.JRadioButton jatrasados;
    private javax.swing.JRadioButton jcancelados;
    private javax.swing.JRadioButton jconcluidos;
    private javax.swing.JTextField jdataPedido;
    private javax.swing.JTextField jdataPrevista;
    private javax.swing.JRadioButton jpendentes;
    private javax.swing.JTable jtabelaItens;
    private javax.swing.JRadioButton jtodos;
    private javax.swing.JTextField jtotalPedido;
    // End of variables declaration//GEN-END:variables
}
