/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.FachadaControle;
import controle.GerenciadorClientes;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.entidades.Cliente;
import persistencia.entidades.Produto;
import persistencia.entidades.Usuario;
import persistencia.entidades.Veiculo;

/**
 *
 * @author Bruno
 */
public class JanelaConsultaClientes extends javax.swing.JDialog {
    
    private List<Cliente> lista;
    private JFrame pai;
    private Cliente cliente = null;
        
    /**
     * Creates new form JanelaConsultaProdutos
     */
    public JanelaConsultaClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pai = (JFrame) parent;
        
        this.setLocationRelativeTo(null);
        jbutaoAdicionar.setVisible(false);
        try {
            this.consultar();
        } catch (Exception ex) {
            Logger.getLogger(JanelaConsultaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(FachadaControle.getFachadaControle().getUsuarioLogado().getTipo().equals(Usuario.TIPO_VENDEDOR)){
            jbutaoEditar.setEnabled(false);
            jbutaoExcluir.setEnabled(false);
        }
        
    }
    
    public JanelaConsultaClientes(java.awt.Frame parent, boolean modal, Cliente cliente){
        super(parent, modal);
        initComponents();
        this.pai = (JFrame) parent;
        
        this.setLocationRelativeTo(null);
        jbutaoAdicionar.setVisible(true);
        this.cliente = cliente;
        try {
            this.consultar();
        } catch (Exception ex) {
            Logger.getLogger(JanelaConsultaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(FachadaControle.getFachadaControle().getUsuarioLogado().getTipo().equals(Usuario.TIPO_VENDEDOR)){
            jbutaoEditar.setEnabled(false);
            jbutaoExcluir.setEnabled(false);
        }
    }
    
    
//    public JanelaConsultaClientes(java.awt.Frame parent, boolean modal,Produto produto) {
//        super(parent, modal);
//        initComponents();
//        this.setLocationRelativeTo(null);
//        
//        this.jChave.requestFocus();
//        jbutaoAdicionar.setVisible(true);
//        jbutaoEditar.setEnabled(false);
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jChave = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelaclientes = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jbutaoAdicionar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbutaoExcluir = new javax.swing.JButton();
        jbutaoEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabelacarros = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jplaca = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE CLIENTES");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa por Nome ou Apelido"));
        jPanel1.setToolTipText("Pesquisa");

        jChave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChaveActionPerformed(evt);
            }
        });
        jChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jChaveKeyPressed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.png"))); // NOI18N
        jButton7.setText("BUSCAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jChave, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addGap(384, 384, 384))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados dos Clientes"));

        jtabelaclientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtabelaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Apelido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabelaclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelaclientesMouseClicked(evt);
            }
        });
        jtabelaclientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtabelaclientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtabelaclientes);
        if (jtabelaclientes.getColumnModel().getColumnCount() > 0) {
            jtabelaclientes.getColumnModel().getColumn(0).setResizable(false);
            jtabelaclientes.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtabelaclientes.getColumnModel().getColumn(1).setResizable(false);
            jtabelaclientes.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtabelaclientes.getColumnModel().getColumn(2).setResizable(false);
            jtabelaclientes.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Parar.png"))); // NOI18N
        jButton6.setText("FECHAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jbutaoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jbutaoAdicionar.setText("PÁTIO");
        jbutaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaoAdicionarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbutaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lixeira2.png"))); // NOI18N
        jbutaoExcluir.setText("EXCLUIR");
        jbutaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaoExcluirActionPerformed(evt);
            }
        });

        jbutaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar.png"))); // NOI18N
        jbutaoEditar.setText("EDITAR");
        jbutaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaoEditarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Carros do Cliente"));

        jtabelacarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo", "Ano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabelacarros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtabelacarrosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtabelacarros);
        if (jtabelacarros.getColumnModel().getColumnCount() > 0) {
            jtabelacarros.getColumnModel().getColumn(0).setResizable(false);
            jtabelacarros.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtabelacarros.getColumnModel().getColumn(1).setResizable(false);
            jtabelacarros.getColumnModel().getColumn(1).setPreferredWidth(130);
            jtabelacarros.getColumnModel().getColumn(2).setResizable(false);
            jtabelacarros.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Novo.png"))); // NOI18N
        jButton2.setText("NOVO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca Por Placa"));

        jplaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jplaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jplacaKeyPressed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa2.png"))); // NOI18N
        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jplaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbutaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbutaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbutaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton1)
                        .addComponent(jbutaoExcluir)
                        .addComponent(jbutaoEditar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbutaoAdicionar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            this.consultar();
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jtabelaclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelaclientesMouseClicked
        int codigo = jtabelaclientes.getSelectedRow();
        
        this.adicionarTabelaVeiculos(this.lista.get(codigo));
    }//GEN-LAST:event_jtabelaclientesMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jtabelaclientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtabelaclientesKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
        }if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            int codigo = jtabelaclientes.getSelectedRow();
            this.adicionarTabelaVeiculos(this.lista.get(codigo+1));
        }if(evt.getKeyCode() == KeyEvent.VK_UP){
            int codigo = jtabelaclientes.getSelectedRow();
            this.adicionarTabelaVeiculos(this.lista.get(codigo-1));
        }if(evt.getKeyCode() == KeyEvent.VK_TAB){
            this.jtabelacarros.requestFocus();
        }
        
        
    }//GEN-LAST:event_jtabelaclientesKeyPressed

    private void jChaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jChaveKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                this.consultar();
            } catch (Exception ex) {
                Logger.getLogger(JanelaConsultaClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
            jtabelaclientes.requestFocus();
        }else{
            
        }
    }//GEN-LAST:event_jChaveKeyPressed

    private void jChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChaveActionPerformed
        
    }//GEN-LAST:event_jChaveActionPerformed

    private void jbutaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaoAdicionarActionPerformed
        this.adicionar();
    }//GEN-LAST:event_jbutaoAdicionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        FachadaControle.getFachadaControle().gerarReltorioClientes((ArrayList<Cliente>) this.lista, "Clientes");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbutaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaoExcluirActionPerformed
        int sim = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o cliente?", "Exclusão", JOptionPane.YES_NO_OPTION);
        if(sim == JOptionPane.YES_OPTION){
            int i = jtabelaclientes.getSelectedRow();
            int codigo = this.lista.get(i).getCodigo();


            try {
                this.excluir(codigo);
                JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jbutaoExcluirActionPerformed

    private void jbutaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaoEditarActionPerformed
        int i = jtabelaclientes.getSelectedRow();
        Cliente cliente = this.lista.get(i);
        JanelaEditarClientes cadastroCliente = new JanelaEditarClientes(pai, true,cliente);
        cadastroCliente.setVisible(true);
        this.meteNaTabela();
        
    }//GEN-LAST:event_jbutaoEditarActionPerformed

    private void jtabelacarrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtabelacarrosKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.adicionar();
        }
    }//GEN-LAST:event_jtabelacarrosKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JanelaCadastroClientes cd = new JanelaCadastroClientes(this.pai, true);
        cd.setVisible(true);
        this.consultar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.consultarPlaca();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jplacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jplacaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                this.consultarPlaca();
            } catch (Exception ex) {
                Logger.getLogger(JanelaConsultaClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
            jtabelaclientes.requestFocus();
        }else{
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jplacaKeyPressed

    public void adicionar(){
        int i = jtabelaclientes.getSelectedRow();
        int j = jtabelacarros.getSelectedRow();
        if(j > -1 && i > -1){
            Cliente c = this.lista.get(i);
            Veiculo v = c.getVeiculos().get(j);

    //        c.setVeiculos(new ArrayList<Veiculo>());
    //        c.getVeiculos().add(v);

            cliente.setCodigo(c.getCodigo());
            cliente.setNome(c.getNome());
            cliente.setApelido(c.getApelido());
            cliente.setBairro(c.getBairro());
            cliente.setCelular(c.getCelular());
            cliente.setTelefone(c.getTelefone());
            cliente.setCep(c.getCep());
            cliente.setCpf(c.getCpf());
            cliente.setRg(c.getRg());
            cliente.setEndereco(c.getEndereco());
            cliente.setNumero(c.getNumero());
            cliente.setObservacao(c.getObservacao());
            cliente.setStatus(c.getStatus());
            cliente.setSexo(c.getSexo());

            cliente.setVeiculos(new ArrayList<Veiculo>());
            cliente.getVeiculos().add(v);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Cliente e um Veículo!");
        }
    }
    
    
    public void excluir(int codigo) throws Exception{
        if(codigo == 1)
            throw new Exception("Cliente PADRÃO não pode ser excluído");
        
        FachadaControle.getFachadaControle().excluirCliente(codigo);
        DefaultTableModel modelo = (DefaultTableModel) jtabelaclientes.getModel();
        DefaultTableModel modelocarros = (DefaultTableModel) jtabelacarros.getModel();
            //Limpa a tabela antes de adicionar os novos dados
        int c = jtabelaclientes.getSelectedRow();
        modelo.removeRow(c);
            
        int t = modelocarros.getRowCount();
        for(int i=0;i<t;i++){
            modelocarros.removeRow(0);
        }
    }
    
    public void consultar(){
        try {
            lista = FachadaControle.getFachadaControle().consultaClientes(jChave.getText());
            this.meteNaTabela();
        } catch (Exception ex) {
            Logger.getLogger(JanelaConsultaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public void consultarPlaca(){
        try {
            Veiculo veiculo = FachadaControle.getFachadaControle().getVeiculo(jplaca.getText());
            
            if(veiculo != null){
                this.lista = FachadaControle.getFachadaControle().consultaClientes(veiculo);
                this.meteNaTabela();
            }else{
                JOptionPane.showMessageDialog(null, "Veículo de placa '"+jplaca.getText()+"' não encontrado!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(JanelaConsultaClientes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    private void meteNaTabela(){
        DefaultTableModel modelo = (DefaultTableModel) jtabelaclientes.getModel();
        DefaultTableModel modelocarros = (DefaultTableModel) jtabelacarros.getModel();
            //Limpa a tabela antes de adicionar os novos dados
            int tam = modelo.getRowCount();
            for(int i=0;i<tam;i++){
                modelo.removeRow(0);
            }
            
            tam = modelocarros.getRowCount();
            for(int i=0;i<tam;i++){
                modelocarros.removeRow(0);
            }
            
            for (Cliente cliente : lista) {
                String[] linha = new String[3];
                linha[0] = cliente.getCodigo()+"";
                linha[1] = cliente.getNome();
                linha[2] = cliente.getApelido();
                modelo.addRow(linha);
    
            }
                       
    }
    
    private void adicionarTabelaVeiculos(Cliente cliente){
        DefaultTableModel modelo = (DefaultTableModel) jtabelacarros.getModel();
        
            //Limpa a tabela antes de adicionar os novos dados
            int tam = modelo.getRowCount();
            for(int i=0;i<tam;i++){
                modelo.removeRow(0);
            }
                String[] linha = new String[3];
                for (Veiculo veiculo : cliente.getVeiculos()) {
                    linha[0] = veiculo.getPlaca();
                    linha[1] = veiculo.getModelo();
                    linha[2] = veiculo.getAno()+"";
                    modelo.addRow(linha);
                }
                
            
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the dialog
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                JanelaConsultaProdutos dialog = new JanelaConsultaProdutos(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JTextField jChave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbutaoAdicionar;
    private javax.swing.JButton jbutaoEditar;
    private javax.swing.JButton jbutaoExcluir;
    private javax.swing.JTextField jplaca;
    private javax.swing.JTable jtabelacarros;
    private javax.swing.JTable jtabelaclientes;
    // End of variables declaration//GEN-END:variables
}
