/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.processos.BuscaProduto;
import visao.auxiliar.Arquivo;
import controle.FachadaControle;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;
import persistencia.entidades.Fornecedor;
import persistencia.entidades.Grupo;
import persistencia.entidades.Produto;

/**
 *
 * @author Bruno
 */
public class JanelaConsultaProdutosVenda extends javax.swing.JDialog {
    
    private Produto produto;
    private ArrayList<Produto> lista;
    private JFrame pai;
        
    /**
     * Creates new form JanelaConsultaProdutos
     */
    public JanelaConsultaProdutosVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pai = (JFrame) parent;
        
        this.setLocationRelativeTo(null);
        jbutaoAdicionar.setVisible(false);
        
    }
    
    public JanelaConsultaProdutosVenda(java.awt.Frame parent, boolean modal,Produto produto) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        //this.buscarProduto();
        this.produto = produto;
        this.jChave.requestFocus();
        jbutaoAdicionar.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jChave = new javax.swing.JTextField();
        jbutaobuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaPesquisa = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jbutaoAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE PRODUTOS");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa por Nome"));
        jPanel1.setToolTipText("Pesquisa");

        jChave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChaveActionPerformed(evt);
            }
        });
        jChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jChaveKeyPressed(evt);
            }
        });

        jbutaobuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.png"))); // NOI18N
        jbutaobuscar.setText("BUSCAR");
        jbutaobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaobuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jChave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbutaobuscar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutaobuscar)
                    .addComponent(jChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jTabelaPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Estoque", "Preço", "Fabricante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaPesquisaMouseClicked(evt);
            }
        });
        jTabelaPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabelaPesquisaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaPesquisa);
        if (jTabelaPesquisa.getColumnModel().getColumnCount() > 0) {
            jTabelaPesquisa.getColumnModel().getColumn(0).setResizable(false);
            jTabelaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTabelaPesquisa.getColumnModel().getColumn(1).setResizable(false);
            jTabelaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTabelaPesquisa.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Parar.png"))); // NOI18N
        jButton6.setText("FECHAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jbutaoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jbutaoAdicionar.setText("ADICIONAR");
        jbutaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaoAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbutaoAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jbutaoAdicionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutaobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaobuscarActionPerformed
        this.buscarProduto();
    }//GEN-LAST:event_jbutaobuscarActionPerformed

    private void jTabelaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaPesquisaMouseClicked
        if(evt.getClickCount() == 2){
            this.mandarProdutoPraVenda();
        }   
    }//GEN-LAST:event_jTabelaPesquisaMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTabelaPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaPesquisaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.mandarProdutoPraVenda();
        }if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jTabelaPesquisaKeyPressed

    private void jChaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jChaveKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.buscarProduto();
        }else if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
            jTabelaPesquisa.requestFocus();
        }else{
            this.buscarProduto();
        }if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jChaveKeyPressed

    private void jChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChaveActionPerformed
        
    }//GEN-LAST:event_jChaveActionPerformed

    private void jbutaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaoAdicionarActionPerformed
        this.mandarProdutoPraVenda();
    }//GEN-LAST:event_jbutaoAdicionarActionPerformed

    public void mandarProdutoPraVenda(){
        //String codigo = (String)jTabelaPesquisa.getValueAt(jTabelaPesquisa.getSelectedRow(), 0);
        try {
            //produto = new Produto();
            //Produto p = FachadaControle.getFachadaControle().buscaProdutoBarra(codigo);
            
            int codigo = jTabelaPesquisa.getSelectedRow();
            //Produto p = this.lista.get(codigo);
            Produto p = (Produto) jTabelaPesquisa.getValueAt(codigo, 1);
            p = FachadaControle.getFachadaControle().getProduto(p.getCodigo());
            produto.setCodigo(p.getCodigo());
            produto.setCodigoBarra(p.getCodigoBarra());
            produto.setCodigoproduto(p.getCodigoproduto());
            produto.setDescricao(p.getDescricao());
            produto.setEstoqueAtual(p.getEstoqueAtual());
            produto.setEstoqueMinimo(p.getEstoqueMinimo());
            produto.setFabricante(p.getFabricante());
            produto.setPrecoCusto(p.getPrecoCusto());
            produto.setPrecoVenda(p.getPrecoVenda());
            produto.setFoto(p.getFoto());
            produto.setStatus(p.getStatus());
            
//            produto.setNomeFoto(p.getNomefoto());
            produto.setGrupo(p.getGrupo());
            produto.setSimilares(p.getSimilares());
            produto.setFornecedor(p.getFornecedor());
            //JOptionPane.showMessageDialog(null, produto.getCodigo() + " - "+produto.getDescricao());
            this.dispose();
       } catch (SQLException ex) {
//            Logger.getLogger(JanelaConsultaProdutosVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void buscarProduto(){
        this.lista = new ArrayList<>();
        BuscaProduto processo = new BuscaProduto(jTabelaPesquisa, jChave.getText(), lista);
        processo.start();
    }
    
//    private void buscarProduto(){
//
//        
//        
//        this.lista = new ArrayList<>();
////            if(jradiotodos.isSelected()){
////                BuscaProduto busca = new BuscaProduto(jTabelaPesquisa,jChave.getText(), this.lista);
////                busca.start();
////            }else{
////                BuscaProduto busca = new BuscaProduto(jTabelaPesquisa,jChave.getText(), this.lista,true);
////                busca.start();
////        }
//        
//        
//        JanelaEsperando janela = new JanelaEsperando(pai, true, jTabelaPesquisa, jChave.getText(), lista, true);
//        janela.setVisible(true);
//           
//        System.out.println("teste");
// 
//    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the dialog
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                JanelaConsultaProdutos dialog = new JanelaConsultaProdutos(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jChave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaPesquisa;
    private javax.swing.JButton jbutaoAdicionar;
    private javax.swing.JButton jbutaobuscar;
    // End of variables declaration//GEN-END:variables
}
