/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.auxiliar.Arquivo;
import controle.FachadaControle;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.entidades.Item;
import persistencia.entidades.Venda;
import visao.auxiliar.JCalendar;

/**
 *
 * @author Bruno
 */
public class JanelaConsultaVendas extends javax.swing.JDialog {
    
    private List<Venda> lista;
    private Venda venda;
    /**
     * Creates new form JanelaConsultaProdutos
     */
    public JanelaConsultaVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.lista = null;
        this.venda = null;
        this.jbutao_abrir.setVisible(false);
    }
    
    public JanelaConsultaVendas(java.awt.Frame parent, boolean modal, Venda venda){
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.buscarOrcamentos();
        this.venda = venda;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jdataInicial = new visao.auxiliar.JCalendar(false);
        jdataFinal = new visao.auxiliar.JCalendar(false);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaItens = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jInicio = new javax.swing.JTextField();
        jFim = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabelavendas = new javax.swing.JTable();
        jbutao_abrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE VENDAS");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Período das Vendas"));
        jPanel1.setToolTipText("Pesquisa");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.png"))); // NOI18N
        jButton7.setText("BUSCAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jdataInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdataInicialActionPerformed(evt);
            }
        });

        jdataFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setText("Data Inicial");

        jLabel2.setText("Data Final");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar.png"))); // NOI18N
        jButton1.setText("ORÇAMENTOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jdataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jdataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens da Venda"));

        jTabelaItens.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "QTD", "PREÇO", "TOTAL", "DESC. %", "VENDEDOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaItensMouseClicked(evt);
            }
        });
        jTabelaItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabelaItensKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaItens);
        if (jTabelaItens.getColumnModel().getColumnCount() > 0) {
            jTabelaItens.getColumnModel().getColumn(0).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTabelaItens.getColumnModel().getColumn(1).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTabelaItens.getColumnModel().getColumn(2).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTabelaItens.getColumnModel().getColumn(3).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTabelaItens.getColumnModel().getColumn(4).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTabelaItens.getColumnModel().getColumn(5).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTabelaItens.getColumnModel().getColumn(6).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Parar.png"))); // NOI18N
        jButton6.setText("FECHAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jButton5.setText("IMPRIMIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados das Vendas"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("TOTAL DO RELATÓRIO");

        jTotal.setEditable(false);
        jTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("INICIO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("FIM:");

        jInicio.setEditable(false);
        jInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFim.setEditable(false);
        jFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jFim))
                .addGap(18, 48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTotal))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendas Pesquisadas"));

        jtabelavendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Cliente", "Data", "Pagamento", "Total", "Desconto", "Vendedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabelavendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelavendasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtabelavendas);
        if (jtabelavendas.getColumnModel().getColumnCount() > 0) {
            jtabelavendas.getColumnModel().getColumn(0).setResizable(false);
            jtabelavendas.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtabelavendas.getColumnModel().getColumn(1).setResizable(false);
            jtabelavendas.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtabelavendas.getColumnModel().getColumn(2).setResizable(false);
            jtabelavendas.getColumnModel().getColumn(2).setPreferredWidth(30);
            jtabelavendas.getColumnModel().getColumn(3).setResizable(false);
            jtabelavendas.getColumnModel().getColumn(3).setPreferredWidth(20);
            jtabelavendas.getColumnModel().getColumn(4).setResizable(false);
            jtabelavendas.getColumnModel().getColumn(4).setPreferredWidth(20);
            jtabelavendas.getColumnModel().getColumn(5).setResizable(false);
            jtabelavendas.getColumnModel().getColumn(5).setPreferredWidth(20);
            jtabelavendas.getColumnModel().getColumn(6).setResizable(false);
            jtabelavendas.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jbutao_abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AbriPasta.png"))); // NOI18N
        jbutao_abrir.setText("ABRIR");
        jbutao_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutao_abrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbutao_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton6))
                    .addComponent(jbutao_abrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabelaItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaItensMouseClicked
          
    }//GEN-LAST:event_jTabelaItensMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTabelaItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaItensKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //this.mandarProdutoPraVenda();
        }
    }//GEN-LAST:event_jTabelaItensKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            FachadaControle.getFachadaControle().gerarRelatorioVendas((ArrayList<Venda>) this.lista, jInicio.getText(), jFim.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.buscarVenda();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jdataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdataInicialActionPerformed

    private void jtabelavendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelavendasMouseClicked
        this.vendaClicada();
    }//GEN-LAST:event_jtabelavendasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.buscarOrcamentos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbutao_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutao_abrirActionPerformed
        // TODO add your handling code here:
        this.enviar();
    }//GEN-LAST:event_jbutao_abrirActionPerformed

    private void enviar(){
        int i = jtabelavendas.getSelectedRow();
        Venda v = this.lista.get(i);
        this.venda.setCodigo(v.getCodigo());
        this.venda.setCaixa(v.getCaixa());
        this.venda.setData(v.getData());
        this.venda.setDesconto(v.getDesconto());
        this.venda.setStatus(v.getStatus());
        this.venda.setTotal(v.getTotal());
        this.venda.setCliente(v.getCliente());
        this.venda.setVendedor(v.getVendedor());
        this.venda.setItens(v.getItens());
        this.dispose();        
    }
    
    public void buscarVenda(){
        DefaultTableModel modelo = (DefaultTableModel) jtabelavendas.getModel();
        int tam = modelo.getRowCount();
        for(int i=0;i<tam;i++){
            modelo.removeRow(0);
        }
        
        String dataInicial = ((JCalendar)jdataInicial).getText();
        String dataFinal = ((JCalendar)jdataFinal).getText();
        
        try {
            if(dataInicial.length() > 0 && dataFinal.length() > 0){
                java.text.SimpleDateFormat formatodata = new java.text.SimpleDateFormat("dd/MM/yyyy"); 

                this.lista = FachadaControle.getFachadaControle().consultaVendas(dataInicial, dataFinal);

                for (Venda venda : lista) {
                    String[] linha = new String[7];
                    linha[0] = venda.getCodigo()+"";
                    linha[1] = venda.getCliente().getNome();
                    linha[2] = formatodata.format(venda.getData());
                    linha[3] = venda.getFormaPagamento();
                    linha[4] = "R$ "+venda.getTotal();
                    linha[5] = venda.getDesconto()+"";
                    linha[6] = venda.getVendedor().getNome();
                    modelo.addRow(linha);
                }

                jInicio.setText(dataInicial);
                jFim.setText(dataFinal);
            }else{
                JOptionPane.showMessageDialog(null, "Data Inválida!");
            }
        } catch (Exception ex) {
            Logger.getLogger(JanelaConsultaVendas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void buscarOrcamentos(){
        DefaultTableModel modelo = (DefaultTableModel) jtabelavendas.getModel();
        int tam = modelo.getRowCount();
        for(int i=0;i<tam;i++){
            modelo.removeRow(0);
        }
        
        String dataInicial = ((JCalendar)jdataInicial).getText();
        String dataFinal = ((JCalendar)jdataFinal).getText();
        
        try {
            java.text.SimpleDateFormat formatodata = new java.text.SimpleDateFormat("dd/MM/yyyy"); 
            
            this.lista = FachadaControle.getFachadaControle().consultaVendas();
            
            for (Venda venda : lista) {
                String[] linha = new String[7];
                linha[0] = venda.getCodigo()+"";
                linha[1] = venda.getCliente().getNome();
                linha[2] = formatodata.format(venda.getData());
                linha[3] = venda.getFormaPagamento();
                linha[4] = "R$ "+venda.getTotal();
                linha[5] = venda.getDesconto()+"";
                linha[6] = venda.getVendedor().getNome();
                modelo.addRow(linha);
            }
            
            jInicio.setText(dataInicial);
            jFim.setText(dataFinal);
        } catch (Exception ex) {
            Logger.getLogger(JanelaConsultaVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void vendaClicada(){
        int s = jtabelavendas.getSelectedRow();
        
        List<Item> itens = this.lista.get(s).getItens();
        
        
        DefaultTableModel model = (DefaultTableModel) jTabelaItens.getModel();
        //Limpa a tabela antes de adicionar os novos dados

        int tam = model.getRowCount();
        for(int i=0;i<tam;i++){
            model.removeRow(0);
        }
                    
            //for(Venda venda : lista){
                for(Item item : itens){
                    String[] linha = new String[7];
                    linha[0] = String.valueOf(item.getProduto().getCodigo());
                    linha[1] = item.getProduto().getDescricao();
                    linha[2] = item.getQuantidade()+"";
                    linha[3] = item.getPreco()+"";
                    linha[4] = item.getTotal()+"";
                    linha[5] = item.getDesconto()+"";
                    model.addRow(linha);
                }
                
            //}
            //jTotal.setText(total+"");
            //jInicio.setText(dataInicial);
            //jFim.setText(dataFinal);
            
            
            jdataInicial.requestFocus();
            //jTabelaPesquisa.requestFocus();
            
        
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the dialog
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                JanelaConsultaProdutos dialog = new JanelaConsultaProdutos(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JTextField jFim;
    private javax.swing.JTextField jInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabelaItens;
    private javax.swing.JTextField jTotal;
    private javax.swing.JButton jbutao_abrir;
    private javax.swing.JComboBox jdataFinal;
    private javax.swing.JComboBox jdataInicial;
    private javax.swing.JTable jtabelavendas;
    // End of variables declaration//GEN-END:variables
}
