/* * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import controle.FachadaControle;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.entidades.Movimento;
import persistencia.entidades.Produto;

/**
 *
 * @author brunn_000
 */
public class JanelaEntradaSaida extends javax.swing.JDialog {

    private Produto produto;
    private TelaPrincipal pai;
    /**
     * Creates new form JanelaEntradaSaida
     */
    public JanelaEntradaSaida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.pai = (TelaPrincipal) parent;
        
        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        jdata.setText(sdf.format(new Date()));
        
      
        produto = new Produto();
        
    }

    public JanelaEntradaSaida(java.awt.Frame parent, boolean modal, Produto produto) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.pai = (TelaPrincipal) parent;
        
        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        jdata.setText(sdf.format(new Date()));
        
        
        jcodigo.setText(produto.getCodigoBarra());
        
        this.buscaProdutoPorCodigo();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtipo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jquantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jprecoCusto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jprecoVenda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jEstoqueAtual = new javax.swing.JTextField();
        jEstoqueMinimo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jdata = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jfoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ENTRADA E SAÍDA DE PRODUTOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Consulta"));

        jcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcodigoKeyPressed(evt);
            }
        });

        jLabel1.setText("Código de Barra do produto");

        jLabel2.setText("Tipo");

        jtipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Entrada", "Saída" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jquantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jquantidade.setText("1");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Descrição");

        jdescricao.setEditable(false);
        jdescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdescricao.setAutoscrolls(false);

        jLabel5.setText("Preço Custo");

        jprecoCusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setText("Preço Venda");

        jprecoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setText("Estoque Atual");

        jEstoqueAtual.setEditable(false);
        jEstoqueAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jEstoqueMinimo.setEditable(false);
        jEstoqueMinimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setText("Estoque Mínimo");

        jLabel9.setText("Data");

        jdata.setEditable(false);
        jdata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jprecoVenda, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jquantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addComponent(jprecoCusto, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jprecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jprecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar.png"))); // NOI18N
        jButton2.setText("SALVAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jfoto, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jfoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.buscarProduto();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcodigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.buscaProdutoPorCodigo();
            
            jquantidade.requestFocus();
            //teste.selectAll();
            jquantidade.selectAll();
            
            
        } else if (evt.getKeyCode() == KeyEvent.VK_F3) {
            this.buscarProduto();
        } else if (evt.getKeyCode() == KeyEvent.VK_F5) {
            
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            //jtabelaitens.requestFocus();
        }
    }//GEN-LAST:event_jcodigoKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double precovenda = Double.parseDouble(jprecoVenda.getText().replaceAll(",", "."));
        double precocusto = Double.parseDouble(jprecoCusto.getText().replaceAll(",", "."));
        
        produto.setPrecoCusto(precocusto);
        produto.setPrecoVenda(precovenda);
        
        Movimento movimento = new Movimento();
        movimento.setProduto(produto);
        movimento.setQuantidade(Integer.parseInt(jquantidade.getText()));
        movimento.setTipo(jtipo.getSelectedItem().toString());
        movimento.setCriadopor(FachadaControle.getFachadaControle().getUsuarioLogado());
        DateFormat df = new java.text.SimpleDateFormat("dd/MM/yyyy");

        try {
            Date d = df.parse(jdata.getText());
            movimento.setData(d);
            FachadaControle.getFachadaControle().cadastrarMovimento(movimento);
            JOptionPane.showMessageDialog(null, movimento.getTipo() + " cadastrada com sucesso!");
            //this.consultarMovimentos();
            this.limpartela();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            jcodigo.requestFocus();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    
    private void limpartela(){
        this.produto = new Produto();
        jcodigo.setText("");
        jquantidade.setText("1");
        jdescricao.setText("");
        jprecoCusto.setText("");
        jprecoVenda.setText("");
        jEstoqueAtual.setText("");
        jEstoqueMinimo.setText("");
        jdata.setText("");
        jfoto.setIcon(null);
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        jdata.setText(sdf.format(new Date()));
        jcodigo.requestFocus();
    }
    private void buscarProduto() {
        JanelaConsultaProdutos janelaconsulta = new JanelaConsultaProdutos(this.pai, true, produto);
        janelaconsulta.setVisible(true);
        if (produto.getCodigo() != 0) {
            jcodigo.setText(produto.getCodigoBarra());
            jdescricao.setText(produto.getDescricao());
            jprecoCusto.setText((""+produto.getPrecoCusto()).replace(".", ","));
            jprecoVenda.setText((""+produto.getPrecoVenda()).replace(".", ","));
            jEstoqueAtual.setText(""+produto.getEstoqueAtual());
            jEstoqueMinimo.setText(""+produto.getEstoqueMinimo());
            
            jquantidade.requestFocus();
            //teste.selectAll();
            jquantidade.selectAll();
            
             //Exibindo a imagem no JLabelprod
           jfoto.setIcon(null);
           ImageIcon img = new ImageIcon(produto.getFoto());
           Image foto = img.getImage().getScaledInstance(jfoto.getWidth(), jfoto.getHeight(), Image.SCALE_DEFAULT);
           jfoto.setIcon(new ImageIcon(foto));
            
        }
    }
    
    
    private void buscaProdutoPorCodigo(){
        //Produto produto = new Produto();
        try {
            produto = FachadaControle.getFachadaControle().buscaProdutoBarra(jcodigo.getText());
            jdescricao.setText(produto.getDescricao());
            jprecoCusto.setText((""+produto.getPrecoCusto()).replace(".", ","));
            jprecoVenda.setText((""+produto.getPrecoVenda()).replace(".", ","));
            jEstoqueAtual.setText(""+produto.getEstoqueAtual());
            jEstoqueMinimo.setText(""+produto.getEstoqueMinimo());
            
            
            jquantidade.setText("1");
            jquantidade.requestFocus();
            jquantidade.select(0, jquantidade.getText().length());
            
//            fos.write(fotodados);
//            fos.close();
            
            //Exibindo a imagem no JLabel
           jfoto.setIcon(null);
           ImageIcon img = new ImageIcon(produto.getFoto());
           Image foto = img.getImage().getScaledInstance(jfoto.getWidth(), jfoto.getHeight(), Image.SCALE_DEFAULT);
           jfoto.setIcon(new ImageIcon(foto));

        } catch (SQLException ex) {
            Logger.getLogger(JanelaVenda.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jEstoqueAtual;
    private javax.swing.JTextField jEstoqueMinimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jcodigo;
    private javax.swing.JTextField jdata;
    private javax.swing.JTextField jdescricao;
    private javax.swing.JLabel jfoto;
    private javax.swing.JTextField jprecoCusto;
    private javax.swing.JTextField jprecoVenda;
    private javax.swing.JTextField jquantidade;
    private javax.swing.JComboBox jtipo;
    // End of variables declaration//GEN-END:variables
}
