/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.processos.BuscaProduto;
import controle.FachadaControle;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.FachadaPersistencia;
import persistencia.entidades.Fornecedor;
import persistencia.entidades.Grupo;
import persistencia.entidades.Produto;
import persistencia.entidades.Produto_fornecedor;
import persistencia.entidades.Usuario;
import visao.processos.BuscaGrupo;

/**
 *
 * @author Bruno
 */
public class JanelaConsultaProdutos extends javax.swing.JDialog {
    
    private FachadaPersistencia banco;
    private Produto produto = null;
    private List<Produto> lista;
    private JFrame pai;
        
    /**
     * Creates new form JanelaConsultaProdutos
     */
    public JanelaConsultaProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.banco = new FachadaPersistencia();
        
        this.pai = (JFrame) parent;
        //produto = new Produto();
        this.setLocationRelativeTo(null);
        jbutaoAdicionar.setVisible(false);
        jradiotodos.setSelected(true);
        //this.buscarProduto();
        this.buscarGrupos();
        this.jChave.requestFocus();
        //jbutaoExcluir.setVisible(false);
        jTabelaPesquisa.setAutoCreateRowSorter(true);
        jtabelasimilar.setAutoCreateRowSorter(true);
        
        if(FachadaControle.getFachadaControle().getUsuarioLogado().getTipo().equals(Usuario.TIPO_VENDEDOR)){
            //jbutaoEditar.setEnabled(false);
            jbutaoEditar.setText("COMPLETO");
            jbutaoExcluir.setEnabled(false);
        }
        
    }
    
    public JanelaConsultaProdutos(java.awt.Frame parent, boolean modal,Produto produto) {
        super(parent, modal);
        initComponents();
        this.banco = new FachadaPersistencia();
        this.setLocationRelativeTo(null);
        //this.buscarProduto();
        this.produto = produto;
        this.jChave.requestFocus();
        jbutaoAdicionar.setVisible(true);
        jbutaoEditar.setEnabled(false);
        jradiotodos.setSelected(true);
        this.buscarGrupos();
        this.buscarProduto();
        this.jChave.requestFocus();
        
        jbutaoExcluir.setVisible(false);
        jTabelaPesquisa.setAutoCreateRowSorter(true);
        jtabelasimilar.setAutoCreateRowSorter(true);
        
        if(FachadaControle.getFachadaControle().getUsuarioLogado().getTipo().equals(Usuario.TIPO_VENDEDOR)){
            //jbutaoEditar.setEnabled(false);
            jbutaoEditar.setText("COMPLETO");
            jbutaoExcluir.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jChave = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jradiotodos = new javax.swing.JRadioButton();
        jradiocriticos = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaPesquisa = new javax.swing.JTable();
        jquadro = new javax.swing.JPanel();
        jfoto = new javax.swing.JLabel();
        jbutaoAdicionar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbutaoEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtabelasimilar = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jgrupos = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jbutaoExcluir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jbuscafor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE PRODUTOS");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa por Nome"));
        jPanel1.setToolTipText("Pesquisa");

        jChave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChaveActionPerformed(evt);
            }
        });
        jChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jChaveKeyPressed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.png"))); // NOI18N
        jButton7.setText("BUSCAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jradiotodos);
        jradiotodos.setText("Todos os Produtos");

        buttonGroup1.add(jradiocriticos);
        jradiocriticos.setText("Produtos Críticos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jChave, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jradiotodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jradiocriticos)
                        .addGap(195, 195, 195))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jradiotodos)
                            .addComponent(jradiocriticos))
                        .addGap(18, 18, 18)
                        .addComponent(jChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jTabelaPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preço", "Est.", "Fabricante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaPesquisa.setColumnSelectionAllowed(true);
        jTabelaPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabelaPesquisaFocusGained(evt);
            }
        });
        jTabelaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaPesquisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabelaPesquisaMouseEntered(evt);
            }
        });
        jTabelaPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabelaPesquisaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaPesquisa);
        jTabelaPesquisa.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTabelaPesquisa.getColumnModel().getColumnCount() > 0) {
            jTabelaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTabelaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(500);
            jTabelaPesquisa.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTabelaPesquisa.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTabelaPesquisa.getColumnModel().getColumn(4).setPreferredWidth(70);
        }

        jquadro.setBackground(new java.awt.Color(255, 255, 255));

        jfoto.setText(".");

        javax.swing.GroupLayout jquadroLayout = new javax.swing.GroupLayout(jquadro);
        jquadro.setLayout(jquadroLayout);
        jquadroLayout.setHorizontalGroup(
            jquadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jquadroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jquadroLayout.setVerticalGroup(
            jquadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jquadroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jquadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jquadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbutaoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jbutaoAdicionar.setText("ADD");
        jbutaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaoAdicionarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbutaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar.png"))); // NOI18N
        jbutaoEditar.setText("EDITAR");
        jbutaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaoEditarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos Similares"));

        jtabelasimilar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preço", "Est.", "Fabricante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtabelasimilar);
        if (jtabelasimilar.getColumnModel().getColumnCount() > 0) {
            jtabelasimilar.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtabelasimilar.getColumnModel().getColumn(1).setPreferredWidth(600);
            jtabelasimilar.getColumnModel().getColumn(2).setPreferredWidth(20);
            jtabelasimilar.getColumnModel().getColumn(3).setPreferredWidth(5);
            jtabelasimilar.getColumnModel().getColumn(4).setPreferredWidth(70);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Por Grupo"));

        jgrupos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jgrupos, 0, 243, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jgrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        jbutaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lixeira2.png"))); // NOI18N
        jbutaoExcluir.setText("Excluir");
        jbutaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaoExcluirActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Por Fornecedor"));

        jbuscafor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa2.png"))); // NOI18N
        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbuscafor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jbuscafor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbutaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbutaoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbutaoEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(2, 2, 2)))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbutaoAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbutaoExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbutaoEditar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.buscarProduto();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTabelaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaPesquisaMouseClicked
        if(evt.getClickCount() == 2){
            if(produto == null){
                //if(!FachadaControle.getFachadaControle().getUsuarioLogado().getTipo().equals(Usuario.TIPO_VENDEDOR)){
                    //this.editar();
                this.ver();
                //}
            }else{
                this.mandarProdutoPraVenda();
            }
        }else{
            this.produtoSelecionado(this.jTabelaPesquisa.getSelectedRow());
        }
    }//GEN-LAST:event_jTabelaPesquisaMouseClicked

    private void jTabelaPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaPesquisaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(produto == null){
                this.ver();
            }else{
                this.mandarProdutoPraVenda();
            }
        }if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            int sel = jTabelaPesquisa.getSelectedRow();
            //if(sel >= 0){
                this.produtoSelecionado(sel+1);
            //}else{
                //this.produtoSelecionado(0);
            //}
        }if(evt.getKeyCode() == KeyEvent.VK_UP){
            int sel = jTabelaPesquisa.getSelectedRow();
            this.produtoSelecionado(sel - 1);
        }
        
        
    }//GEN-LAST:event_jTabelaPesquisaKeyPressed

    private void jChaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jChaveKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.buscarProduto();
        }else if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
            jTabelaPesquisa.requestFocus();
        }/*else{
            this.buscarProduto();
        }*/
    }//GEN-LAST:event_jChaveKeyPressed

    private void jChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChaveActionPerformed
        
    }//GEN-LAST:event_jChaveActionPerformed

    private void jbutaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaoAdicionarActionPerformed
        this.mandarProdutoPraVenda();
    }//GEN-LAST:event_jbutaoAdicionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //FachadaControle.getFachadaControle().gerarRelatorioProdutos(lista, Arquivo.salvaArquivo());
        JanelaGerandoRelatorio janelagerando = new JanelaGerandoRelatorio(pai, lista, true);
        janelagerando.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbutaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaoEditarActionPerformed
        this.editar();
    }//GEN-LAST:event_jbutaoEditarActionPerformed

    private void jTabelaPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabelaPesquisaFocusGained

    }//GEN-LAST:event_jTabelaPesquisaFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Grupo grupo = (Grupo) jgrupos.getSelectedItem();
        //this.lista = new ArrayList<>();
        this.limparTabelas();
        BuscaProduto busca = new BuscaProduto(jTabelaPesquisa,grupo, this.lista);
        busca.start();
        jfoto.setIcon(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTabelaPesquisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaPesquisaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabelaPesquisaMouseEntered

    private void jbutaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaoExcluirActionPerformed
        int valor = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Excluir Produto", JOptionPane.YES_NO_OPTION);
        if(valor == JOptionPane.YES_OPTION){
            int i = jTabelaPesquisa.getSelectedRow();
            Produto p = this.lista.get(i);
            
            p.setStatus("Inativo");

            try {
                //this.banco.excluirProduto(p);
                FachadaControle.getFachadaControle().editarProduto(p);
                //FachadaControle.getFachadaControle().Fechar();
                //this.lista = new ArrayList<>();
                //FachadaControle.getFachadaControle().Abrir();
                
                this.buscarProduto();

                for (Produto pro : lista) {
                    JOptionPane.showMessageDialog(null, pro.getDescricao()+" - "+pro.getStatus());
                }
            } catch (SQLException ex) {
                Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbutaoExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.buscarProdutoFornecedor();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mandarProdutoPraVenda(){
        int codigo = ((Produto)jTabelaPesquisa.getValueAt(jTabelaPesquisa.getSelectedRow(), 1)).getCodigo();
        
        //int i = jTabelaPesquisa.getSelectedRow();
        try {
            Produto p = FachadaControle.getFachadaControle().getProduto(codigo);
            //Produto p = this.lista.get(i);
                        
            produto.setCodigo(p.getCodigo());
            produto.setCodigoBarra(p.getCodigoBarra());
            produto.setCodigoproduto(p.getCodigoproduto());
            produto.setDescricao(p.getDescricao());
            produto.setEstoqueAtual(p.getEstoqueAtual());
            produto.setEstoqueMinimo(p.getEstoqueMinimo());
            produto.setFabricante(p.getFabricante());
            produto.setPrecoCusto(p.getPrecoCusto());
            produto.setPrecoVenda(p.getPrecoVenda());
            produto.setStatus(p.getStatus());
            
            produto.setGrupo(p.getGrupo());
            produto.setFabricante(p.getFabricante());
            produto.setSimilares(p.getSimilares());
            produto.setFornecedor(p.getFornecedor());
            produto.setFoto(p.getFoto());
            
            //JOptionPane.showMessageDialog(null, produto.getCodigo() + " - "+produto.getDescricao());
            this.dispose();
        } catch (SQLException ex) {
            //Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void buscarProduto(){
        this.limparTabelas();

        this.lista = new ArrayList<>();
            if(jradiotodos.isSelected()){
                BuscaProduto busca = new BuscaProduto(jTabelaPesquisa,jChave.getText(), this.lista);
                busca.start();
            }else{
                BuscaProduto busca = new BuscaProduto(jTabelaPesquisa,jChave.getText(), this.lista,true);
                busca.start();
        }
        
        
//        JanelaEsperando janela = new JanelaEsperando(pai, true, jTabelaPesquisa, jChave.getText(), lista, jradiotodos.isSelected());
//        janela.setVisible(true);
           
        jfoto.setIcon(null);
        jChave.requestFocus();
 
    }
    
    public void buscarProdutoFornecedor(){
        Produto_fornecedor profor = new Produto_fornecedor();
        profor.setCodigoFornecedor(jbuscafor.getText());
        BuscaProduto busca = new BuscaProduto(jTabelaPesquisa,profor, this.lista);
        busca.start();                
    }
    
    private void produtoSelecionado(int i){
        //int i = this.jTabelaPesquisa.getSelectedRow();
        //Produto pro = this.lista.get(i);
        String codigo = (String) jTabelaPesquisa.getValueAt(i, 0);
        
        
        jfoto.setIcon(null);
        //byte[] fotodados = produto.getFoto();
        try{
            Produto pro = FachadaControle.getFachadaControle().buscaProdutoBarra(codigo);
//            FileOutputStream fos = new FileOutputStream(produto.getNomefoto()+".jpg"); 
//            fos.write(fotodados);
//            fos.close();
            
            //Exibindo a imagem no JLabelprod
           jfoto.setIcon(null);
           ImageIcon img = new ImageIcon(pro.getFoto());
           Image foto = img.getImage().getScaledInstance(jfoto.getWidth(), jfoto.getHeight(), Image.SCALE_DEFAULT);
           jfoto.setIcon(new ImageIcon(foto));
           
           DefaultTableModel modelo = (DefaultTableModel) jtabelasimilar.getModel();
           int j = jtabelasimilar.getRowCount();
            for (int k = 0; k < j; k++) {
                modelo.removeRow(0);
            }
           
           for (Produto similar : pro.getSimilares()) {
               if(similar.getStatus().equals(Produto.ATIVO)){
                    String[] linha = new String[5];
                    linha[0] = similar.getCodigoproduto();
                    linha[1] = similar.getDescricao();
                    linha[2] = "R$ "+similar.getPrecoVenda()+"";
                    linha[3] = similar.getEstoqueAtual()+"";
                    linha[4] = similar.getFabricante().getNome();
                    modelo.addRow(linha);
               }
           }
           
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void buscarGrupos(){
        try {
            List<Grupo> grupos = FachadaControle.getFachadaControle().buscaGrupo("");
            BuscaGrupo grupo_processo = new BuscaGrupo(jgrupos,grupos);
            grupo_processo.start();
        } catch (SQLException ex) {
            Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
            
         
    }
    
    private void editar(){
        try {
            //String codigo = (String)jTabelaPesquisa.getValueAt(jTabelaPesquisa.getSelectedRow(), 0);
                        //String codigo = this.lista.get(jTabelaPesquisa.getSelectedRow()).getCodigoBarra();
            
            //Produto p = FachadaControle.getFachadaControle().buscaProdutoBarra(codigo);
            Produto p = (Produto) jTabelaPesquisa.getValueAt(jTabelaPesquisa.getSelectedRow(), 1);
            
            p = FachadaControle.getFachadaControle().getProduto(p.getCodigo());
            
            //Produto p = this.lista.get(jTabelaPesquisa.getSelectedRow());
            JanelaCadastroProduto editarProduto = new JanelaCadastroProduto(this.pai, true, p);
            editarProduto.setVisible(true);
            jTabelaPesquisa.setValueAt(p.getPrecoVenda()+"", jTabelaPesquisa.getSelectedRow(), 2);
            jTabelaPesquisa.setValueAt(p.getEstoqueAtual()+"", jTabelaPesquisa.getSelectedRow(), 3);
            this.buscarProduto();
        //} catch (SQLException ex) {
        //    Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        } catch (SQLException ex) {
            Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
//        } catch (SQLException ex) {
//            Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }
    
    public void excluir(){
    
    }
    
    private void ver(){
        try {
            //String codigo = (String)jTabelaPesquisa.getValueAt(jTabelaPesquisa.getSelectedRow(), 0);
                        //String codigo = this.lista.get(jTabelaPesquisa.getSelectedRow()).getCodigoBarra();
            
            //Produto p = FachadaControle.getFachadaControle().buscaProdutoBarra(codigo);
            Produto p = (Produto) jTabelaPesquisa.getValueAt(jTabelaPesquisa.getSelectedRow(), 1);
            
            p = FachadaControle.getFachadaControle().getProduto(p.getCodigo());
            
            //Produto p = this.lista.get(jTabelaPesquisa.getSelectedRow());
            JanelaVer janela = new JanelaVer(this.pai,true,p);
            janela.setVisible(true);
        //} catch (SQLException ex) {
        //    Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        } catch (SQLException ex) {
            Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
//        } catch (SQLException ex) {
//            Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }
    
    private void limparTabelas(){
        DefaultTableModel model = (DefaultTableModel) jTabelaPesquisa.getModel();
        //Limpa a tabela antes de adicionar os novos dados
        int tam = model.getRowCount();
        for(int i=0;i<tam;i++){
            model.removeRow(0);
        }
        
        DefaultTableModel model2 = (DefaultTableModel) jtabelasimilar.getModel();
        //Limpa a tabela antes de adicionar os novos dados
        tam = model2.getRowCount();
        for(int i=0;i<tam;i++){
            model2.removeRow(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the dialog
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                JanelaConsultaProdutos dialog = new JanelaConsultaProdutos(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JTextField jChave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTabelaPesquisa;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jbuscafor;
    private javax.swing.JButton jbutaoAdicionar;
    private javax.swing.JButton jbutaoEditar;
    private javax.swing.JButton jbutaoExcluir;
    private javax.swing.JLabel jfoto;
    private javax.swing.JComboBox jgrupos;
    private javax.swing.JPanel jquadro;
    private javax.swing.JRadioButton jradiocriticos;
    private javax.swing.JRadioButton jradiotodos;
    private javax.swing.JTable jtabelasimilar;
    // End of variables declaration//GEN-END:variables
}
