/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 24/01/2013, 09:28:56
 */
package visao;


import controle.backupador.BackupSupremo;
import controle.FachadaControle;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import persistencia.entidades.Caixa;
import persistencia.entidades.Pedido;
import persistencia.entidades.Produto;
import persistencia.entidades.Usuario;

/**
 *
 * @author USUARIO
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
   //public boolean atualiza;
    private Usuario usuario;
    private List<Produto> produtos;
    private Properties config;
    //private AtualizaTela atualizaTela;
    /** Creates new form TelaPrincipal */
    public TelaPrincipal(Usuario usuario) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                //System.out.println(info.getName());
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e);
        }
        initComponents();
        
        config = new Properties();
        try {
            config.load(new FileInputStream("propriedades.ini"));
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jButton7.setVerticalTextPosition(AbstractButton.BOTTOM);
        jButton7.setHorizontalTextPosition(AbstractButton.CENTER);
        
        Image icone = Toolkit.getDefaultToolkit().getImage("logo.png");
        this.setIconImage(icone);
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.usuario = usuario;
        this.setTitle("SiAP - SISTEMA DE AUTO PEÇAS | USUÁRIO LOGADO: "+this.usuario.getNome());
        
        
        System.out.println(FachadaControle.getFachadaControle().isCaixaAberto());
        System.out.println(FachadaControle.getFachadaControle().getCaixa());
        
        if(FachadaControle.getFachadaControle().getUsuarioLogado().getTipo().equals(Usuario.TIPO_VENDEDOR)){
            this.negarPermissao();
        }
//        Caixa caixa = FachadaControle.getFachadaControle().getCaixa();
//        System.out.println(caixa);
//        if(!FachadaControle.getFachadaControle().isCaixaAberto()){
//            JanelaAbrirCaixa abrircaixa = new JanelaAbrirCaixa(this, true);
//            abrircaixa.setVisible(true);
//        }
//        atualiza = true;
//        this.atualizaTela = new AtualizaTela(this);
//        this.atualizaTela.start();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jcontrole3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmenuCadastroProduto = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmenuGerenciar = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jmenuFecharCaixa = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jmenuDadosEmpresa = new javax.swing.JMenuItem();
        jmenuGerenicarUsarios = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu9.setText("File");
        jMenuBar3.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar3.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SiAP - Sistema Auto Peças");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );

        jcontrole3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bcs_blue_64.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jcontrole3Layout = new javax.swing.GroupLayout(jcontrole3);
        jcontrole3.setLayout(jcontrole3Layout);
        jcontrole3Layout.setHorizontalGroup(
            jcontrole3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcontrole3Layout.createSequentialGroup()
                .addGap(0, 408, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jcontrole3Layout.setVerticalGroup(
            jcontrole3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcontrole3Layout.createSequentialGroup()
                .addGap(0, 166, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jButton3.setText("Alternar Usuários - F9");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vender2Grande.png"))); // NOI18N
        jButton7.setText("Operação de Venda");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtosGrandao.png"))); // NOI18N
        jButton1.setText("Veículo no Pátio");
        jButton1.setToolTipText("");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPreferredSize(new java.awt.Dimension(133, 133));
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        jButton5.setText("Produtos");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes_grande.png"))); // NOI18N
        jButton2.setText("Consulta Clientes");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcontrole3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 77, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcontrole3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 204, 0));

        jMenu3.setText("Vendas");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vender.png"))); // NOI18N
        jMenuItem5.setText("Operação de Venda");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem23.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        jMenuItem23.setText("Carro no Pátio");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem23);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/orçament.png"))); // NOI18N
        jMenuItem3.setText("Consulta de Vendas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Clientes");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clientes.png"))); // NOI18N
        jMenuItem6.setText("Cadastro de Cliente");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lista.png"))); // NOI18N
        jMenuItem1.setText("Consulta de Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Estoque");

        jmenuCadastroProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        jmenuCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        jmenuCadastroProduto.setText("Cadastro de Produtos");
        jmenuCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCadastroProdutoActionPerformed(evt);
            }
        });
        jMenu7.add(jmenuCadastroProduto);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.png"))); // NOI18N
        jMenuItem7.setText("Consulta de Produtos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/entradaSaida.png"))); // NOI18N
        jMenuItem16.setText("Entrada e Saída");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem16);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar.png"))); // NOI18N
        jMenuItem2.setText("Consulta Entrarda e Saída");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jmenuGerenciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AbriPasta.png"))); // NOI18N
        jmenuGerenciar.setText("Gerenciar");

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fabricantes.png"))); // NOI18N
        jMenuItem17.setText("Fabricantes");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jmenuGerenciar.add(jMenuItem17);

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        jMenuItem21.setText("Fornecedores");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jmenuGerenciar.add(jMenuItem21);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/grupos.png"))); // NOI18N
        jMenuItem22.setText("Grupos");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jmenuGerenciar.add(jMenuItem22);

        jMenu7.add(jmenuGerenciar);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Relatórios");

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorioProdutos.png"))); // NOI18N
        jMenuItem20.setText("Relatório de Produtos");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem20);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clientes.png"))); // NOI18N
        jMenuItem9.setText("Relatório de Clientes");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/entradaSaida.png"))); // NOI18N
        jMenuItem12.setText("Relatório Entrada e Saída");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Financeiro");

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa.png"))); // NOI18N
        jMenuItem13.setText("Abrir Caixa");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem13);

        jmenuFecharCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jmenuFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chave.png"))); // NOI18N
        jmenuFecharCaixa.setText("Fechar Caixa");
        jmenuFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuFecharCaixaActionPerformed(evt);
            }
        });
        jMenu8.add(jmenuFecharCaixa);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lista.png"))); // NOI18N
        jMenuItem10.setText("Consulta de Caixas");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jMenuBar1.add(jMenu8);

        jMenu5.setText("Adminstrativo");

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lapis.png"))); // NOI18N
        jMenuItem14.setText("Autoria");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Backup Banco.png"))); // NOI18N
        jMenuItem8.setText("Realizar Backup");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Backup Banco.png"))); // NOI18N
        jMenuItem11.setText("Restaurar Backup");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jmenuDadosEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ferramentas.png"))); // NOI18N
        jmenuDadosEmpresa.setText("Dados Empresa");
        jmenuDadosEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuDadosEmpresaActionPerformed(evt);
            }
        });
        jMenu5.add(jmenuDadosEmpresa);

        jmenuGerenicarUsarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jmenuGerenicarUsarios.setText("Gerenciar Usuários");
        jmenuGerenicarUsarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuGerenicarUsariosActionPerformed(evt);
            }
        });
        jMenu5.add(jmenuGerenicarUsarios);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EditarPessoa.png"))); // NOI18N
        jMenuItem18.setText("Alterar Dados de Usuário");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem18);

        jMenuItem24.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoff.png"))); // NOI18N
        jMenuItem24.setText("Trocar Usuário");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem24);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Parar.png"))); // NOI18N
        jMenuItem15.setText("Fechar o Sistema");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JanelaVenda janelavenda;
        try {
            janelavenda = new JanelaVenda(this, true, this.usuario);
            janelavenda.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
            
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Realizar Backup");
        arquivo.setFileFilter(new FileNameExtensionFilter("Arquivo de backup", "sql"));
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int result = arquivo.showSaveDialog(null);
        
        String caminho = config.getProperty("MYSQL");
        if(caminho == null){
            caminho = "";
        }else{
            caminho += "/";
        }
        
        
        //C:\BC\SIAP\mysql\bin
        BackupSupremo bkp = new BackupSupremo(caminho+"mysql",caminho+"mysqldump","root", "neural", "bancopecas");
        //BackupSupremo bkp = new BackupSupremo("C:\\Users\\Bruno Vicente\\Dropbox\\projetos\\DANIELSIAP\\mysql\\bin\\mysql","C:\\Users\\Bruno Vicente\\Dropbox\\projetos\\DANIELSIAP\\mysql\\bin\\mysqldump","root", "neural", "bancopecas");

        
        if(result == JFileChooser.CANCEL_OPTION){  

        }   
        else{  
          String file = arquivo.getSelectedFile().getAbsolutePath();
          boolean resultado = bkp.fazerBackup(file);
          //;FachadaControle.getFachadaControle().backupDB(file+".sql");
          
          if(resultado){
              JOptionPane.showMessageDialog(null, " Backup criado com sucesso! ");
          }
          else{
              JOptionPane.showMessageDialog(null, " Não foi possível criar o Backup! ");
          }
        }
        

      
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
       JFileChooser arquivo = new JFileChooser();
       
       arquivo.setDialogTitle("Restaurar Backup");
        arquivo.setFileFilter(new FileNameExtensionFilter("Arquivo de backup", "sql"));
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        String caminho = config.getProperty("MYSQL");
        if(caminho == null){
            caminho = "";
        }else{
            caminho += "/";
        }
        
        int result = arquivo.showOpenDialog(null);

        if(result == JFileChooser.CANCEL_OPTION){  

        }   
        else{  
            
            String file = arquivo.getSelectedFile().getAbsolutePath(); 
            BackupSupremo bkp = new BackupSupremo(caminho+"mysql",caminho+"mysqldump","root", "neural", "bancopecas");
            //BackupSupremo bkp = new BackupSupremo("C:\\Users\\Bruno Vicente\\Dropbox\\projetos\\DANIELSIAP\\mysql\\bin\\mysql","C:\\Users\\Bruno Vicente\\Dropbox\\projetos\\DANIELSIAP\\mysql\\bin\\mysqldump","root", "neural", "bancopecas");
            boolean resultado = bkp.recuperarBackup(file);
            //this.setVisible(false);
            JanelaRestauracao janela = new JanelaRestauracao(this, true, file, bkp.getBackupProcess());
            janela.setVisible(true);
            System.exit(0);
        }//Fim do Else
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        if(!FachadaControle.getFachadaControle().isCaixaAberto()){
            JanelaAbrirCaixa abrir = new JanelaAbrirCaixa(this, true);
            abrir.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Caixa já aberto!");
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jmenuFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuFecharCaixaActionPerformed
        if(FachadaControle.getFachadaControle().isCaixaAberto()){
            JanelaFecharCaixa fechar = new JanelaFecharCaixa(this, true);
            fechar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Não há caixa aberto!");
        }
    }//GEN-LAST:event_jmenuFecharCaixaActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        int sim = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do Sistema?", "Sair", JOptionPane.YES_NO_OPTION);
        if(sim == JOptionPane.YES_OPTION){
                System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jmenuGerenicarUsariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuGerenicarUsariosActionPerformed
        JanelaConultaUsuarios consultaUsuarios = new JanelaConultaUsuarios(this, true);
        consultaUsuarios.setVisible(true);
    }//GEN-LAST:event_jmenuGerenicarUsariosActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        EditarUsuario janelaEditar = new EditarUsuario(this, true);
        janelaEditar.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        if(FachadaControle.getFachadaControle().getCaixa() != null){
//            int sim = JOptionPane.showConfirmDialog(null, "Há um CAIXA aberto, deseja fechá-lo?", "Caixa Aberto", JOptionPane.YES_NO_OPTION);
//            if(sim == JOptionPane.YES_OPTION){
//                JanelaFecharCaixa caixa = new JanelaFecharCaixa(this, true);
//                caixa.setVisible(true);
//            }
//        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(!FachadaControle.getFachadaControle().isCaixaAberto()){
            JanelaAbrirCaixa abrircaixa = new JanelaAbrirCaixa(this, true);
            abrircaixa.setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JanelaConsultaClientes consultaCliente = new JanelaConsultaClientes(this, true);
        consultaCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmenuCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCadastroProdutoActionPerformed
        JanelaCadastroProduto cadastroProduto = new JanelaCadastroProduto(this, true);
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_jmenuCadastroProdutoActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JanelaCadastroClientes cadastroCliente = new JanelaCadastroClientes(this, true);
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JanelaConsultaProdutos consultaProdutos = new JanelaConsultaProdutos(this, true);
        consultaProdutos.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        JanelaEntradaSaida janela = new JanelaEntradaSaida(this, true);
        janela.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        try {
            JanelaCarroPatio janelacarro = new JanelaCarroPatio(this, true, usuario);
            janelacarro.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        JanelaConsultaFabricantes janelafab = new JanelaConsultaFabricantes(this, true);
        janelafab.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        JanelaConsultaFornecedor janelafor = new JanelaConsultaFornecedor(this, true);
        janelafor.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        JanelaConsultaGrupo janelagrup = new JanelaConsultaGrupo(this, true);   
        janelagrup.setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jmenuDadosEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuDadosEmpresaActionPerformed
        JanelaDadosEmpresa dadosempresa = new JanelaDadosEmpresa(this, true);
        dadosempresa.setVisible(true);
    }//GEN-LAST:event_jmenuDadosEmpresaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            JanelaVenda janelavenda = new JanelaVenda(this, true, usuario);
            janelavenda.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JanelaConsultaProdutos produto = new JanelaConsultaProdutos(this, true);
        produto.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JanelaCarrosPatio janelacarro = new JanelaCarrosPatio(this, usuario,true);
            janelacarro.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JanelaConsultaClientes consultacliente = new JanelaConsultaClientes(this, true);
        consultacliente.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        JanelaRelatoriosCliente janelarelatorios = new JanelaRelatoriosCliente(this, true);
        janelarelatorios.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        JanelaRelatorios janelarelatorios = new JanelaRelatorios(this, true);
        janelarelatorios.setVisible(true);
        //        try {
            //            ArrayList<Produto> lista = (ArrayList<Produto>) FachadaControle.getFachadaControle().buscaProduto("");
            //            JanelaGerandoRelatorio processo = new JanelaGerandoRelatorio(this, lista, true);
            //            processo.setVisible(true);
            //        } catch (SQLException ex) {
            //            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JanelaConsultaMovimentos janela = new JanelaConsultaMovimentos(this, true);
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JanelaConsultaVendas jcv = new JanelaConsultaVendas(this, true);
        jcv.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        JanelaRelatórioEntradaSaida jres = new JanelaRelatórioEntradaSaida(this, true);
        jres.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        JanelaConsultaCaixa janela = new JanelaConsultaCaixa(this, true);
        janela.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        TelaAutoria janela = new TelaAutoria(this, true);
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    public void negarPermissao(){
        jmenuCadastroProduto.setEnabled(false);
        jmenuDadosEmpresa.setEnabled(false);
        jmenuFecharCaixa.setEnabled(false);
        jmenuGerenciar.setEnabled(false);
        jmenuGerenicarUsarios.setEnabled(false);
    }
    
    public void produtosPendentes(){
        try {
            Caixa caixa = FachadaControle.getFachadaControle().getCaixa();
            
            List<Produto> lista = FachadaControle.getFachadaControle().buscaProduto("");
            List<Produto> pendentes = new ArrayList<Produto>();
                        
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            List<Pedido> pedidos = FachadaControle.getFachadaControle().consultaPedidosAtrasados(sdf.format(new Date()));
            
            for(Produto p : lista){
                if(p.getEstoqueAtual() < p.getEstoqueMinimo()){
                    pendentes.add(p);
                }
            }
                        
            //Cria a janela caso há pedidos pendentes
            if((caixa != null) && (pedidos.size() > 0)){
                jcontrole3.removeAll();
                JanelaPainelPedidos painelPedidos = new JanelaPainelPedidos(pedidos);
                jcontrole3.add(painelPedidos);
                painelPedidos.setVisible(true);
            }else{
                jcontrole3.removeAll();
                jcontrole3.repaint();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//Fim dos produtos pendentes
    
    public void mostrarCaixaAberto(){
        Caixa caixa = FachadaControle.getFachadaControle().getCaixa();
        
            if(caixa != null){
                System.out.println("Atualizando Caixa...");
                JanelaPainelCaixa painelcaixa = new JanelaPainelCaixa(caixa);
                painelcaixa.setVisible(true);
            }
        
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new TelaPrincipal().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jcontrole3;
    private javax.swing.JMenuItem jmenuCadastroProduto;
    private javax.swing.JMenuItem jmenuDadosEmpresa;
    private javax.swing.JMenuItem jmenuFecharCaixa;
    private javax.swing.JMenu jmenuGerenciar;
    private javax.swing.JMenuItem jmenuGerenicarUsarios;
    // End of variables declaration//GEN-END:variables

     
    
    
    

}
